### PR TITLE
Add empty bids for aol

### PR DESCRIPTION
**Pull request by mmilleruva**
Ensure an empty response is always returned for aol bids.

Here is a gist for showing the bid responses:
https://gist.github.com/mmilleruva/30ed49cc7a17e15e631c2610db9d19a3
You can copy it into the bids back handler for Prebid. 

After this change aol should consistently be zero. I use the following commands run from the Prebid.js repo to copy a local build into AdVantage.js
```zsh
gulp build-bundle-dev --modules=../ad-vantage.js/modules.json
cp build/dev/prebid.js ../ad-vantage.js/src/support/cached_prebid.js
```

I did not find such an obvious fix for the AppNexus adapter which is used by districtM. However looking at this chart: https://kibana.studybreakmedia.com/goto/19ddfac12c89d4ab22bc8ecc424e8420
DistrictM might be a small enough part of revenue that we could just try turning them off.

### CODE REVIEW

**Comment by Carsair** [comment]
@mmilleruva Brealtime also uses this adapter right? Have we tried using the "AST" version of the appnexus adapter?

**Comment by mmilleruva** [comment]
AST adapter

**Comment by mmilleruva** [comment]
AST is a good idea. My thought would be to see

**Comment by Carsair** [comment]
## MASTER
### CM
screen shot 2018-02-16 at 11 23 28 am
screen shot 2018-02-16 at 11 23 07 am

###  EB
screen shot 2018-02-16 at 11 22 09 am
screen shot 2018-02-16 at 11 21 44 am

## THIS BRANCH
### CM
screen shot 2018-02-16 at 11 28 40 am
screen shot 2018-02-16 at 11 28 17 am

### EB
screen shot 2018-02-16 at 11 29 39 am
screen shot 2018-02-16 at 11 29 17 am

**Comment by Carsair** [comment]
@mmilleruva Style checks failing for the AOL adapter

**Comment by mmilleruva** [comment]
@Carsair Good call, I was putting it into the bidsBack handler so I wasn't seeing that issue

**Pull request merged**
